name: Build and Package Extension

on:
  push:
    tags:
      - 'v*'  # 仅在打 tag 时触发构建
  workflow_dispatch:  # 也可以手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up dist folder
        run: |
          mkdir dist
          zip -r dist/whmcs-lang-switcher.zip . -x ".git/*" ".github/*"
          cp dist/whmcs-lang-switcher.zip dist/whmcs-lang-switcher.xpi

      - name: Upload Chrome ZIP as Artifact
        uses: actions/upload-artifact@v4
        with:
            name: whmcs-lang-switcher-zip
            path: dist/whmcs-lang-switcher.zip

      - name: Upload Firefox XPI as Artifact
        uses: actions/upload-artifact@v4
        with:
            name: whmcs-lang-switcher-xpi
            path: dist/whmcs-lang-switcher.xpi


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/whmcs-lang-switcher.zip
            dist/whmcs-lang-switcher.xpi
